### PR TITLE
3.6.0 Release

### PR DESCRIPTION
**Pull request by WeiliangChenOIST**

### CODE REVIEW

**Comment by WeiliangChenOIST** [comment]
@tristan0x do we have CI for the public release?

**Comment by tristan0x** [comment]
Not for the moment. I will run the on BB5 manually

**Comment by tristan0x** [comment]
> Not for the moment. I will run the on BB5 manually

* [x] BB5 build and unit-tests
* [x] STEPS_Validation serial test
* [x]  STEPS_Validation parallel test
* [ ] Docker image / rebuild of Jupyter notebooks (in progress)

**Review by tristan0x — APPROVED** [review]
All tests good for me

**Comment by WeiliangChenOIST** [comment]
unit tests fail for API2 on Mac due to a threading issue. As discussed with @jlallouette this is unlikely STEPS related, and shouldn't affect the user. Thus we will address it after the release.

**Pull request merged**
