### PR TITLE
4.0.0 Release

### PR DESCRIPTION
**Pull request by WeiliangChenOIST**
Python API
----------

Introduce a new parallel stochastic reaction-diffusion solver and a deterministic
membrane potential solver named `DistTetOpSplit`. The solver is based on a 
distributed mesh named `DistMesh`.

Build and Packaging
-------------------
1. STEPS requires a C++ compiler compatible with C++ 17.
1. New CMake variables to enable profiling of the simulation:
   `STEPS_USE_LIWKID_PROFLING`, `STEPS_USE_CALIPER_PROFILING`, and `STEPS_USE_NATIVE_PROFILING`
   see [doc/dev/README.md] for more details on how to use it.
1. Add support to Apple M1
1. Add support to compilers GCC 11, LLVM 13, and Apple Clang 13

### CODE REVIEW

**Comment by WeiliangChenOIST** [comment]
@tristan0x let's do some final tests.

**Comment by cattabiani** [comment]
**Validations**
- [ ] rallpack1
- [ ] rallpack3
- [ ] caburst

**Comment by cattabiani** [comment]
I am not sure about caburst validations. I would like to do another round of tests with different seeds. I cannot put myself as reviewer and block this pr. @WeiliangChenOIST may I join the group of developers?

**Comment by WeiliangChenOIST** [comment]
invitation sent.

**Review by cattabiani — CHANGES_REQUESTED** [review]
caburst is giving mixed results. Probably a fluke of the statistics. I want more data before approving. WIP (for me. No action required for you atm)

**Review by cattabiani — APPROVED** [review]
The graph in caburst is still a little e shaking. However, comparing different se

**Review by tristan0x — APPROVED** [review]
LGTM

**Pull request merged**
