### PR TITLE
3.1.0 release

### PR DESCRIPTION
**Pull request by WeiliangChenOIST**

### CODE REVIEW

**Comment by WeiliangChenOIST** [comment]
@FrancescoCasalegno Done.

**Comment by WeiliangChenOIST** [comment]
@FrancescoCasalegno @adevress Anaconda Docker build fails.
[Dockerfile.txt](https://github.com/CNS-OIST/STEPS/files/1103786/Dockerfile.txt)

```
[ 90%] Building CXX object test/unit/cpp/CMakeFiles/test_rng.dir/test_rng.cpp.o
../../../src/libsteps.so.3.1.0: undefined reference to `GOMP_parallel@GOMP_4.0'
collect2: error: ld returned 1 exit status
make[2]: *** [test/unit/cpp/test_tetmesh] Error 1
test/unit/cpp/CMakeFiles/test_tetmesh.dir/build.make:98: recipe for target 'test/unit/cpp/test_tetmesh' failed
make[1]: *** [test/unit/cpp/CMakeFiles/test_tetmesh.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:500: recipe for target 'test/unit/cpp/CMakeFiles/test_tetmesh.dir/all' failed
[ 91%] Linking CXX executable test_membership
[ 92%] Linking CXX executable test_checkid
[ 92%] Built target test_membership
../../../src/libsteps.so.3.1.0: undefined reference to `GOMP_parallel@GOMP_4.0'
collect2: error: ld returned 1 exit status
test/unit/cpp/CMakeFiles/test_checkid.dir/build.make:98: recipe for target 'test/unit/cpp/test_checkid' failed
make[2]: *** [test/unit/cpp/test_checkid] Error 1
CMakeFiles/Makefile2:578: recipe for target 'test/unit/cpp/CMakeFiles/test_checkid.dir/all' failed
make[1]: *** [test/unit/cpp/CMakeFiles/test_checkid.dir/all] Error 2
[ 93%] Linking CXX executable test_rng
../../../src/libsteps.so.3.1.0: undefined reference to `GOMP_parallel@GOMP_4.0'
collect2: error: ld returned 1 exit status
make[2]: *** [test/unit/cpp/test_rng] Error 1
test/unit/cpp/CMakeFiles/test_rng.dir/build.make:98: recipe for target 'test/unit/cpp/test_rng' failed
CMakeFiles/Makefile2:617: recipe for target 'test/unit/cpp/CMakeFiles/test_rng.dir/all' failed
make[1]: *** [test/unit/cpp/CMakeFiles/test_rng.dir/all] Error 2
make: *** [all] Error 2
Makefile:138: recipe for target 'all' failed
The command '/bin/sh -c cmake DUSE_MPI=False -DUSE_PETSC=False .. && make -j4 && make install' returned a non-zero code: 2
```

**Comment by WeiliangChenOIST** [comment]
@FrancescoCasalegno could either you or Adrien check the Anaconda docker compiling issue please?

**Comment by FrancescoCasalegno** [comment]
@WeiliangChenOIST which OS are you running? are you trying to use a docker image?

**Comment by WeiliangChenOIST** [comment]
@FrancescoCasalegno there is a Docker file above, the Docker system is Ubuntu + Anaconda

**Comment by ferdonline** [comment]
The issue seems to be with the Docker image. Some packages part of Anaconda were built with another Gcc, which has a different version of openMP, as described here
https://github.com/jupyter/docker-stacks/issues/177

**Comment by WeiliangChenOIST** [comment]
> The issue seems to be with the Docker image. Some packages part of Anaconda were built with another Gcc, which has a different version of openMP, as described here
> jupyter/docker-stacks#177

In that case I think we can go ahead :)

**Comment by ferdonline** [comment]
@WeiliangChenOIST 
You can find the fixed Docker file
[Dockerfile.txt](https://github.com/CNS-OIST/STEPS/files/1108615/Dockerfile.txt)

I must say that compiling things for Anaconda is not trivial since they have their own stack, and therefore we need to use their gcc/glibc... Another possibility is to remove the dependency on openBlas, openmp

**Pull request merged**
